const heroSet = {
    FloridaMan: {
        id: 2,
        name: 'Florida Man',
        attack: 20,
        max_hp: 400,
        max_mp: 200,
        speed: 5,
        color: 'yellow',
        img: 'https://i.imgur.com/1UlK16x.png',
        type: 'Aries',
    },
    Ed: {
        id: 1,
        name: 'Ed',
        attack: 30,
        max_hp: 300,
        max_mp: 200,
        speed: 10,
        color: 'white',
        img: 'https://i.imgur.com/sEOYWsX.png',
        type: 'Hominid',
    },
    YesMan: {
        id: 3,
        name: 'Yes Man',
        attack: 50,
        max_hp: 200,
        max_mp: 400,
        speed: 7,
        color: 'green',
        img: 'https://i.imgur.com/IJovsH2.png',
        type: 'Lutheran',
    },
    SchoolNurse: {
        id: 4,
        name: 'School Nurse',
        attack: 60,
        max_hp: 190,
        max_mp: 400,
        speed: 8,
        color: 'white',
        img: 'https://i.imgur.com/3dWyEYZ.png',
        type: 'Psybend',
    },
    NeighborhoodDealer: {
        id: 5,
        name: 'Neighborhood Dealer',
        attack: 65,
        max_hp: 420,
        max_mp: 420,
        speed: .3,
        color: 'green',
        img: 'https://i.imgur.com/O9oig22.png',
        type: 'CHOOCH',
    },
    ConservativeGrandad: {
        id: 6,
        name: 'Conservative Grandad',
        attack: 25,
        max_hp: 600,
        max_mp: 250,
        speed: 1,
        color: 'blue',
        img: 'https://i.imgur.com/scbOFR3.png',
        type: 'Sheikh',
    },
    JeffBezos: {
        id: 7,
        name: 'Jeff Bezos',
        attack: 50,
        max_hp: 200,
        max_mp: 400,
        speed: 12,
        color: 'gold',
        img: 'https://i.imgur.com/0vPPtTy.png',
        type: 'Sapphire',
    },
    TikTokTimmy: {
        id: 8,
        name: 'Tik Tok Timmy',
        attack: 45,
        max_hp: 190,
        max_mp: 400,
        speed: 4,
        color: 'yellow',
        img: 'https://i.imgur.com/H7sKMIz.png',
        type: 'Fink',
    },
    DogeCoinDaddy: {
        id: 9,
        name: 'Doge Coin Daddy',
        attack: 20,
        max_hp: 400,
        max_mp: 200,
        speed: 5,
        color: 'yellow',
        img: 'https://i.imgur.com/P92rHca.png',
        type: 'Yuvy',
    },
    GretaThunberg: {
        id: 10,
        name: 'Greta Thunberg',
        attack: 30,
        max_hp: 300,
        max_mp: 200,
        speed: 10,
        color: 'white',
        img: 'https://i.imgur.com/jEl4Evm.png',
        type: 'Sapphire',
    },
    JehovaGeorge: {
        id: 11,
        name: 'Jehova George',
        attack: 50,
        max_hp: 200,
        max_mp: 400,
        speed: 2,
        color: 'Purple',
        img: 'https://i.imgur.com/a8fIb5y.png',
        type: 'Sheikh',
    },
    JoeRoganFan: {
        id: 12,
        name: 'Joe Rogan Fan',
        attack: 10,
        max_hp: 50,
        max_mp: 400,
        speed: 20,
        color: 'white',
        img: 'https://i.imgur.com/yhknUfr.png',
        type: 'Chooch',
    },
    GibbyTheClown: {
        id: 13,
        name: 'Gibby The Clown',
        attack: 55,
        max_hp: 420,
        max_mp: 420,
        speed: 420,
        color: 'green',
        img: 'https://i.imgur.com/64WJLLf.png',
        type: 'Lotus',
    },
    InternetTroll: {
        id: 14,
        name: 'InTeRneT Tr011',
        attack: 25,
        max_hp: 600,
        max_mp: 250,
        speed: 1,
        color: 'blue',
        img: 'https://i.imgur.com/wFE4LM9.png',
        type: 'Sheikh',
    },
    DrProfessorCarl: {
        id: 15,
        name: 'Dr Professer Carl',
        attack: 50,
        max_hp: 200,
        max_mp: 400,
        speed: 12,
        color: 'gold',
        img: 'https://i.imgur.com/jxQRV4Q.png',
        type: 'Sapphire',
    },
    ChuckyCheese: {
        id: 16,
        name: 'Chucky Cheese',
        attack: 45,
        max_hp: 190,
        max_mp: 400,
        speed: 4,
        color: 'yellow',
        img: 'https://i.imgur.com/xJShzrZ.png',
        type: 'Fink',
    },
    PaintballPaul: {
        id: 17,
        name: 'Paintball Paul',
        attack: 55,
        max_hp: 420,
        max_mp: 420,
        speed: 420,
        color: 'green',
        img: 'https://i.imgur.com/t7sF4PS.png',
        type: 'Aries',
    },
    TheColonel: {
        id: 18,
        name: 'The Colonel',
        attack: 25,
        max_hp: 600,
        max_mp: 250,
        speed: 1,
        color: 'blue',
        img: 'https://i.imgur.com/yaPAZoa.png',
        type: 'Sheikh',
    },
    LilSoundcloud: {
        id: 19,
        name: 'Lil Soundcloud',
        attack: 50,
        max_hp: 200,
        max_mp: 400,
        speed: 12,
        color: 'gold',
        img: 'https://i.imgur.com/M7d1N1K.png',
        type: 'Lotus',
    },
    Karen: {
        id: 20,
        name: 'Karen',
        attack: 75,
        max_hp: 150,
        max_mp: 400,
        speed: 4,
        color: 'yellow',
        img: 'https://i.imgur.com/oi8zLK1.png',
        type: 'Psybend',
    },
    SocialMediaActivist: {
        id: 21,
        name: 'Social Media Activist',
        attack: 80,
        max_hp: 140,
        max_mp: 400,
        speed: 4,
        color: 'red',
        img: 'https://i.imgur.com/ka4DKrQ.png',
        type: 'Aries',
    },
    MrMeowz: {
        id: 22,
        name: 'Mr Meowz',
        attack: 666,
        max_hp: 666,
        max_mp: 666,
        speed: 666,
        color: 'red',
        img: 'https://i.imgur.com/Bgvg9n4.png',
        type: 'Ghastly',
    },



}

const monsterSet = {
    Leeches: {
        id: 41,
        name: 'Leeche',
        attack: 10,
        max_hp: 50,
        max_mp: 0,
        speed: 12,
        icon: '',
        color:'black',
        img: 'https://i.imgur.com/o09IdzH.png',
        type: 'Sprite',
    },
    Gluttons: {
        id: 42,
        name: 'Glutton',
        attack: 30,
        max_hp: 100,
        max_mp: 0,
        speed: 2,
        icon: '',
        color:'black',
        img: 'https://i.imgur.com/2xXMktX.png',
        type: 'Magnarock',
    },
    JellyFires: {
        id: 43,
        name: 'Jelly Fire',
        attack: 20,
        max_hp: 200,
        max_mp: 0,
        speed: 7,
        icon: '',
        color:'black',
        img: 'https://i.imgur.com/Q06fVmP.png',
        type: 'Ghastly',
    },
    AncientSpirit: {
        id: 44,
        name: 'Ancient Spirit',
        attack: 25,
        max_hp: 500,
        max_mp: 0,
        speed: 4,
        icon: '',
        color:'black',
        img: 'https://i.imgur.com/gn5GO5c.png',
        type: 'Psybend',
    },
    NatasMinion: {
        id: 45,
        name: 'Natas Minion',
        attack: 40,
        max_hp: 500,
        max_mp: 0,
        speed: 2,
        icon: '',
        color:'black',
        img: 'https://i.imgur.com/wq93xpX.png',
        type: 'Magnarock',
    },
}

module.exports = {heroSet, monsterSet}